FORMAT: 1A

# Energy API
Today is Thursday

This is my Energy API. Demoed on 25th of May, 2016.

## Customer [/customer]
This is a customer resource.

### View [GET]
- Response 200 (application/json; charset=utf-8)
    - Attributes (Customer)

# Data Structures

# Customer (object)
- id: 122132 (number)
- name: Z 
- email: z@apiary.io
- address
    - street
    - city
- reports (array[Usage Report])

# Usage Report (object)
- gas_usage
- gas_cost (number) - Price in USD
- electricity_usage: 12323 (number) - Usage of Electricity in kWh.
