FORMAT: 1A

# Energy API
This is my Energy API.

## Customer [/customer]

This is a customer resources.

### View [GET]
- Response 200 (application/json; charset=utf-8)
    - Attributes (Customer)
        
        

# Data Structures

# Customer (object)
- name: Z 
- email: z@apiary.io
- address
    - street
    - city
- reports (array[Usage Report])

# Usage Report (object)
- gas_usage
- gas_cost (number) - Price in USD
- electricity_usage: 12323 (number) - Usage of Electricity in kWh.
